# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper-unfuddle"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luis Hurtado"]
  s.date = "2012-05-15"
  s.description = "Unfuddle provider for taskmapper implemented with ActiveResource"
  s.email = "luis@hybridgroup.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/provider/comment.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/provider/unfuddle.rb",
    "lib/taskmapper-unfuddle.rb",
    "lib/unfuddle/unfuddle-api.rb",
    "spec/comments_spec.rb",
    "spec/fixtures/comments.xml",
    "spec/fixtures/comments/0.xml",
    "spec/fixtures/comments/2.xml",
    "spec/fixtures/comments/3.xml",
    "spec/fixtures/comments/create.xml",
    "spec/fixtures/projects.xml",
    "spec/fixtures/projects/33041.xml",
    "spec/fixtures/projects/33042.xml",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/tickets.xml",
    "spec/fixtures/tickets/476814.xml",
    "spec/fixtures/tickets/476816.xml",
    "spec/fixtures/tickets/476834.xml",
    "spec/fixtures/tickets/create.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taskmapper-unfuddle_spec.rb",
    "spec/tickets_spec.rb",
    "taskmapper-unfuddle.gemspec"
  ]
  s.homepage = "http://github.com/hybridgroup/taskmapper-unfuddle"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "The Unfuddle provider for taskmapper."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<taskmapper>, ["~> 0.8"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
    else
      s.add_dependency(%q<taskmapper>, ["~> 0.8"])
      s.add_dependency(%q<addressable>, ["~> 2.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<taskmapper>, ["~> 0.8"])
    s.add_dependency(%q<addressable>, ["~> 2.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
  end
end

